name: 'reactive-readme'
description: 'Replaces a section of the README with the value'
inputs:
  value: 
    description: 'The value to set the template to.'
    required: true
    default: ''
  section:  
    description: 'The section of the README to update.'
    required: false
    default: 'section'
  github_token:
    default: ${{ github.token }}
  branch:
    default: ${{ github.event.repository.default_branch }}
    description: The target branch to update.
runs:
  using: 'node12'
  main: 'index.js'